Title =  "Loving life and dreams."
LanguageCode = "zh-CN"
BaseUrl = "https://lisenhui.cn/"
Theme =  "hugo-theme-next"
MetaDataFormat =  "yaml"
PaginatePath =  "p"
Paginate = 10
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"
enableRobotsTXT = true

[Params]
  Introduce = "再平凡的人也有属于他的梦想！"
  Description = "凡梦星尘 | 博客 | 软件 | 架构 | Java | Kylin"
  Keywords =  "凡梦星尘,独立,博客,程序员,架构师,个人,思考,分享,Kylin"
  Subtitle = "Don't stop running forward!"
  AuthorImg = "/img/avatar.png"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
# 开启标签云
  TagCloud = true
# 开启评论功能[Valine, LiveRe]
  Comment = "Valine"
  LiveReId = ""
# 开启BShare分享功能
  Share = "bshare"
  ShareId = ""
# 开启3D访问地球
  RevolverMapId = "5s83wolvn69"
# Learn Cloud
  LCAppId  = ""
  LCAppKey = ""
  LCServer = ""
# 开启站点访问统计代码
# CNZZ统计
  CNNZSiteId = ""
  BusuanziCounter = true
  BaiduSiteId = ""
  GoogleSiteId = ""

[Author]
  Name = "凡梦星尘"

[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5

[Permalinks]
  post = "/:year/:month/:day/:slug/"

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 2
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 3
[[Menu.Main]]
  Name = "公益404"
  Pre = "heartbeat"
  URL = "/404.html"
  Weight = 4

# 个人社交平台
[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/elkan1788/"

[[Params.Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/fan-meng-xing-chen-1"

# 友情链接
[[Params.Links]]
  Name = "Nutz"
  Permalink = "https://nutzam.com/"

[[Params.Links]]
  Name = "JFinal"
  Permalink = "https://jfinal.com/"

[[Params.Links]]
  Name = "Wendal"
  Permalink = "http://wendal.net/"

[[Params.Links]]
  Name = "廖雪峰"
  Permalink = "https://www.liaoxuefeng.com/"

# 压缩开关(HTTPS流量挺贵的,哈)
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
