Title =  "Loving life and dreams."

DefaultContentLanguage = "zh-cn"
LanguageCode = "zh-CN"

Theme =  "hugo-theme-next"

MetaDataFormat =  "toml"

PaginatePath =  "p"
Paginate = 5

DisablePathToLower =  false
PreserveTaxonomyNames = false

PygmentsStyle = "emacs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

enableRobotsTXT = true

enableEmoji = true

ignoreErrors = ["error-remote-getjson"]

[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5

[Permalinks]
  post = "/:year/:month/:day/:slug"

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/xml"
    baseName = "searchindex"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[[Params.Links]]
  Name = "Qybit's Blog"
  Permalink = "https://qybit.gitee.io/"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true