name: sync-2-gitee

on:
  push:
    branches: [main, gh-pg]

jobs:
  sync-2-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:elkan1788/hugo-theme-next.git
          destination-repo: git@gitee.com:lisenhui/hugo-theme-next.git

  reload-pages:
    needs: sync-2-gitee
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages by GitAction
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: elkan1788@gmail.com
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: lisenhui/hugo-theme-next
          branch: gh-pg